### ISSUE TITLE
File url's resolving to a host

### ISSUE THREAD

**Issue by rnentjes** [ebean-orm/ebean-idea-enhancer#15]
Under windows the paths picked up from the module classpaths are trying to resolve to a host (the drivename e.g. C). Due to timeouts this makes the build very slow (incremental builds take 15 - 20 seconds in our case, otherwise less than 1).

See pull request #14 

Our work around atm is adding an entry in the hosts file for host "C".

**Comment by rbygrave** [comment]
This change is now in, fixed in 10.1.6c ... thanks for the PR and ticket, appreciated !!
