### ISSUE TITLE
Update to 11.9.1 agent with profile location support and improvements for Kotlin partial compile

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean-idea-enhancer#26]

**Comment by tobias-** [comment]
Not sure if it matters to you @rbygrave , but this "works for me" :) , and given how much trouble we've had earlier, that means something to me. 

-- edit: sorry if I messed up being funny, but I'm trying to emphasize my joy that the partial compile didn't break anything in our build and 'just works'

**Comment by rbygrave** [comment]
Ah yes ... the partial compile issue with Kotlin was a right pain. I believe we have a good solution released now so it is really nice !!!  I better close this an tidy up here :)
