### ISSUE TITLE
Ebean enhancer configuration in Git

### ISSUE THREAD

**Issue by ajcamilo** [ebean-orm/ebean-idea-enhancer#29]
This intellij plugin puts it's configuration in the `workspace.xml` file of the intellij settings folder.

Because this file is usually on `.gitignore`, the configuration that the project needs the ebean enhancement is not "persisted" in the repository.

Do you think it would be a good idea to change the storage to save the settings in `ebean.xml`?

```
@State(name = "ebeanEnhancement", storages = {
    @Storage(id = "ebeanEnhancement", file = "ebean.xml")
})
```

**Comment by rbygrave** [comment]
Yeah ... maybe "ebean-idea.xml" ?  Sounds like a good idea.  People could just add it to .gitignore if they didn't want it in the git repo.

**Comment by ajcamilo** [comment]
Yes, the only problem I see is that people that already have the plugin configured, when they update to this new version, they will lose their configuration.

Do you want me to make a pull request for this?

**Comment by rbygrave** [comment]
Ok, the new version of the plugin has changed the storage to be in ebean-plugin.xml.  Note that this file is put under the `.idea` directory (for directory based idea storage) so it still isn't really going to be included given people generally .gitignore the `.idea` directory.

Refer to the new plugin at: https://github.com/ebean-orm-tools/ebean-idea-enhancer

**Comment by ajcamilo** [comment]
Awesome, already tried and works like a charm :)
