### ISSUE TITLE
Please put "Ebean Enhancement" toggle in settings as well.

### ISSUE THREAD

**Issue by kreiger** [ebean-orm/ebean-idea-enhancer#30]
My ebean entitites were not being enhanced for some reason.
I searched in "Settings" but could not find anything related to "ebean" except the plugin itself under "Plugins" -> "Installed".

Eventually i stumbled on the toggle in the "Build" menu, and saw it was disabled.
I enabled it and at first it didn't help.
I figured out that i also needed to force a rebuild, and then i finally got it to work.

It took me way too long to find this toggle.
Please create an "Ebean" page in "Settings" where the toggle can also be found.

**Comment by rbygrave** [comment]
Thanks for the feedback.  Yes, would be good to add a settings page.  Let me know if you (or others) have done a Idea settings page or good example etc (to help speed up the development of this).

Thanks, Rob.

**Comment by rbygrave** [comment]
Ok, I have done this in the new version of the plugin at: https://github.com/ebean-orm-tools/ebean-idea-enhancer

This has been submitted to Jetbrains so should be approved and available shortly.

**Comment by rbygrave** [comment]
I'll close this, we can re-open if the new plugin doesn't release for some reason.

**Comment by kreiger** [comment]
Sweet, thanks!
