### ISSUE TITLE
Could not initialize class com.avaje.ebean.Ebean

### ISSUE THREAD

**Issue by raulamoretti** [ebean-orm/ebean-idea-enhancer#8]
Hey guys, Sometimes I get this error:

java.lang.NoClassDefFoundError: Could not initialize class com.avaje.ebean.Ebean 

I think it is about maven or pom.xml whit this plug-in.

**Comment by rbygrave** [comment]
Closing.  Can you raise this issue on the forum - https://groups.google.com/forum/#!forum/ebean
... which is actively monitored by many people etc. 

Thanks.
